# **LOGISTIC REGRESSION** - TITANIC DATA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [3]:
df = df.select_dtypes(exclude=int)
df

sex   age     fare embarked   class    who  adult_male deck  \
0      male  22.0   7.2500        S   Third    man        True  NaN   
1    female  38.0  71.2833        C   First  woman       False    C   
2    female  26.0   7.9250        S   Third  woman       False  NaN   
3    female  35.0  53.1000        S   First  woman       False    C   
4      male  35.0   8.0500        S   Third    man        True  NaN   
..      ...   ...      ...      ...     ...    ...         ...  ...   
886    male  27.0  13.0000        S  Second    man        True  NaN   
887  female  19.0  30.0000        S   First  woman       False    B   
888  female   NaN  23.4500        S   Third  woman       False  NaN   
889    male  26.0  30.0000        C   First    man        True    C   
890    male  32.0   7.7500        Q   Third    man        True  NaN   

     embark_town alive  alone  
0    Southampton    no  False  
1      Cherbourg   yes  False  
2    Southampton   yes   True  
3    Southampton   yes  False  
4    Southampton    no   True  
..           ...   ...    ...  
886  Southampton    no   True  
887  Southampton   yes   True  
888  Southampton    no  False  
889    Cherbourg   yes   True  
890   Queenstown    no   True  

[891 rows x 11 columns]

FOR NOMINAL DATA -> LabelEncoder

FOR ORDINAL DATA -> OrdinalEncoder

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df[['sex']])
df['embark_town'] = le.fit_transform(df[['embark_town']])
df['who'] = le.fit_transform(df[['who']])
df['alive'] = le.fit_transform(df[['alive']])
df

sex   age     fare embarked   class  who  adult_male deck  embark_town  \
0      1  22.0   7.2500        S   Third    1        True  NaN            2   
1      0  38.0  71.2833        C   First    2       False    C            0   
2      0  26.0   7.9250        S   Third    2       False  NaN            2   
3      0  35.0  53.1000        S   First    2       False    C            2   
4      1  35.0   8.0500        S   Third    1        True  NaN            2   
..   ...   ...      ...      ...     ...  ...         ...  ...          ...   
886    1  27.0  13.0000        S  Second    1        True  NaN            2   
887    0  19.0  30.0000        S   First    2       False    B            2   
888    0   NaN  23.4500        S   Third    2       False  NaN            2   
889    1  26.0  30.0000        C   First    1        True    C            0   
890    1  32.0   7.7500        Q   Third    1        True  NaN            1   

     alive  alone  
0        0  False  
1        1  False  
2        1   True  
3        1  False  
4        0   True  
..     ...    ...  
886      0   True  
887      1   True  
888      0  False  
889      1   True  
890      0   True  

[891 rows x 11 columns]

In [5]:
df['who'].unique()

array([1, 2, 0])

In [6]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['First', 'Second', 'Third']])
df['class'] = oe.fit_transform(df[['class']])
df

sex   age     fare embarked  class  who  adult_male deck  embark_town  \
0      1  22.0   7.2500        S    2.0    1        True  NaN            2   
1      0  38.0  71.2833        C    0.0    2       False    C            0   
2      0  26.0   7.9250        S    2.0    2       False  NaN            2   
3      0  35.0  53.1000        S    0.0    2       False    C            2   
4      1  35.0   8.0500        S    2.0    1        True  NaN            2   
..   ...   ...      ...      ...    ...  ...         ...  ...          ...   
886    1  27.0  13.0000        S    1.0    1        True  NaN            2   
887    0  19.0  30.0000        S    0.0    2       False    B            2   
888    0   NaN  23.4500        S    2.0    2       False  NaN            2   
889    1  26.0  30.0000        C    0.0    1        True    C            0   
890    1  32.0   7.7500        Q    2.0    1        True  NaN            1   

     alive  alone  
0        0  False  
1        1  False  
2        1   True  
3        1  False  
4        0   True  
..     ...    ...  
886      0   True  
887      1   True  
888      0  False  
889      1   True  
890      0   True  

[891 rows x 11 columns]

In [7]:
df['class'].unique()

array([2., 0., 1.])

In [8]:
df.drop(columns=['embarked'], inplace = True)
df.drop(columns = ['adult_male'], inplace = True)
df.drop(columns = ['deck'], inplace = True)
df.drop(columns = ['alone'], inplace = True)
df.drop(columns = ['who'], inplace = True)
df

sex   age     fare  class  embark_town  alive
0      1  22.0   7.2500    2.0            2      0
1      0  38.0  71.2833    0.0            0      1
2      0  26.0   7.9250    2.0            2      1
3      0  35.0  53.1000    0.0            2      1
4      1  35.0   8.0500    2.0            2      0
..   ...   ...      ...    ...          ...    ...
886    1  27.0  13.0000    1.0            2      0
887    0  19.0  30.0000    0.0            2      1
888    0   NaN  23.4500    2.0            2      0
889    1  26.0  30.0000    0.0            0      1
890    1  32.0   7.7500    2.0            1      0

[891 rows x 6 columns]

In [9]:
df.isnull().sum()

sex              0
age            177
fare             0
class            0
embark_town      0
alive            0
dtype: int64

In [10]:
df['age'].fillna(df['age'].median(), inplace=True)
df.isnull().sum()

sex            0
age            0
fare           0
class          0
embark_town    0
alive          0
dtype: int64

In [11]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size = 0.8)
model.fit(x_train, y_train)

LogisticRegression()

In [14]:
x

sex   age     fare  class  embark_town
0      1  22.0   7.2500    2.0            2
1      0  38.0  71.2833    0.0            0
2      0  26.0   7.9250    2.0            2
3      0  35.0  53.1000    0.0            2
4      1  35.0   8.0500    2.0            2
..   ...   ...      ...    ...          ...
886    1  27.0  13.0000    1.0            2
887    0  19.0  30.0000    0.0            2
888    0  28.0  23.4500    2.0            2
889    1  26.0  30.0000    0.0            0
890    1  32.0   7.7500    2.0            1

[891 rows x 5 columns]

In [15]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1])

In [16]:
from sklearn.metrics import accuracy_score, recall_score
accuracy_score(y_test, y_pred)

0.7932960893854749

In [17]:
recall_score(y_test, y_pred)

0.8